### ISSUE TITLE
Replace magic numbers with variables

### ISSUE THREAD

**Issue by qwrtln** [Heegu-sama/Homm3BG#10]
There are magic numbers in the documents which are repeated many times. For instance, `[6pt]` occurs 76 times. All values like that should be identified and replaced with variables.

Things to take care of:
- [x] Paragraph `[6pt]`
- [x] Path to images `assets/images`
- [x] Path to SVGs `assets/svgs`
- [ ] `height=10px`
- [ ] Repeated `scale=...`

**Comment by Heegu-sama** [comment]
I'll fix the [6pt]s using the following package and replacing them with \par to force a new paragraph: \usepackage[skip=6pt, indent=0pt]{parskip}

**Comment by qwrtln** [comment]
I'll try to identify some more like these. If we fix them, we'll make the document a lot easier to work with.
