### ISSUE TITLE
Clarification on hand refresh

### ISSUE THREAD

**Issue by omoprof** [Heegu-sama/Homm3BG#107]
"Draw back to your Hand Limit" (p. 9)

It should explicitly say that drawing cards up to limit is not required. 
(Original rules: "At the start of your turn you become the active player and you may discard from your hand as many cards as you want, then you may draw cards up to your hand limit")

In rare cases it is better not to draw cards

**Comment by Heegu-sama** [comment]
Nice observation. I'll add that.

**Comment by Heegu-sama** [comment]
Added this in the next PR I'm working on.
