### ISSUE TITLE
Addition to trading post

### ISSUE THREAD

**Issue by omoprof** [Heegu-sama/Homm3BG#110]
"Exchange resources or Remove a card. See Trading." (p. 42)

You should add mention of buying war machines and link to that section. And add war machine factory to the field list

**Comment by qwrtln** [comment]
I guess we could move all the locations from "Expansion Content" chapter to "All Map Locations", which currently are War Machine Factory and Random Town. Technically, Star Axis is also expansion content, but it's already in the latter.
