### ISSUE TITLE
Addition to paralysis

### ISSUE THREAD

**Issue by omoprof** [Heegu-sama/Homm3BG#113]
Should unit retaliate if it gets paralyzed by an attack ability? Rule book states only about cases when unit already paralyzed. Paralyze section need rewording or addition of that case.

Unit does retaliate in that case, yes

**Comment by qwrtln** [comment]
It's simple to do. Please create a PR with this.

**Comment by Heegu-sama** [comment]
If a unit is paralyzed during an attack that will cause it to retaliate (eg. it's hit by Basilisks or Azure Dragons) it will retaliate as normal. In this game paralysis only stops their next activation, and retaliating isn't considered to be an activation.

This could be clarified with one additional sentence such as "Paralysis does not prevent units from retaliating." I can add this a bit later if you don't want to.

**Comment by Heegu-sama** [comment]
Added this sentence in the AI heroes PR.
