### ISSUE TITLE
Clarification on "beginning of a turn" actions order

### ISSUE THREAD

**Issue by omoprof** [Heegu-sama/Homm3BG#118]
Cases like this
https://boardgamegeek.com/thread/3274669/when-does-at-the-beginning-of-your-turn-happen

I assume order is: hand refill -> buildings effects

**Comment by qwrtln** [comment]
I don't think so, that would make Necropolis heroes significantly stronger than any other faction. I agree that the wording on the building tile could be more fortunate.

**Comment by omoprof** [comment]
rulebook definitely needs some sort of diagram on actions order. Same with beginning of the round buildings
something like

Game Turn
  (order needs confirmation) Drawing astrologers card / Collecting resources -> Drawing Event
  (order needs confirmation) Buildings with beginnig of the round trigger

  Player(x) Turn
    (order needs confirmation) Buildings with beginnig of your turn trigger
    (order needs confirmation) Refill hand

**Comment by qwrtln** [comment]
Over-explaining things like this would just cause tonnes of unnecessary text and confusion. Special cases like that are better left out for FAQ.

**Comment by omoprof** [comment]
https://boardgamegeek.com/thread/3257058/article/43884421#43884421
Aleksander Kubiak said, refill hand first, then buildings

Beginning of the turn on page 9 needs rewording or addition of extra step, something along the lines: resolve building or other effects. And same for round structure on previous page, I guess

**Comment by qwrtln** [comment]
Which ones are the beginning of the round? Do they contradict this?
![image](https://github.com/Heegu-sama/Homm3BG/assets/5611195/51cb8c25-f1e3-436f-85cd-6c79fdda6765)

**Comment by Heegu-sama** [comment]
![image](https://github.com/Heegu-sama/Homm3BG/assets/159418426/be25c041-3ca6-4f57-8e0e-fc52d19f3255)
Adding a third bullet point here to cover this.
