### ISSUE TITLE
Combat wording

### ISSUE THREAD

**Issue by evilmint** [Heegu-sama/Homm3BG#135]
I'm thinking about making the combat wording more specific as in whom you can combat - the enemies (not specifically players, because the enemy can also be an AI):

Current text:
```
Combat with \textbf{another player} can start in two ways:
\begin{itemize}
  \item You move into any Field containing one of their Heroes.
  \item You move into a Town or Settlement owned by them.
```

Suggested:

```
Combat with \textbf{an enemy} Hero can start in two ways:
\begin{itemize}
  \item You move into any Field containing one of an enemy Heroes.
  \item You move into a Town or Settlement owned by the enemy.
```

Let me know if that makes sense

**Comment by qwrtln** [comment]
Sounds reasonable, can you make a PR with this?

**Comment by evilmint** [comment]
Created - https://github.com/Heegu-sama/Homm3BG/pull/146
