### ISSUE TITLE
translation with po4a

### ISSUE THREAD

**Issue by BasileSugranes** [Heegu-sama/Homm3BG#136]
Hello, I tried to use po4a to start working on a translation and I ran into this error while trying to update the document (with `po4a --no-update po4a.cfg`)
Error : 
![issue](https://github.com/Heegu-sama/Homm3BG/assets/49030785/8301363e-2984-47b7-9285-d6ea0a1b7d65)

I managed to solve by adding a line in .cfg to force po4a to consider UTF-8 to be the encoding for all LaTeX files :
![solve](https://github.com/Heegu-sama/Homm3BG/assets/49030785/564c71da-533e-44bd-beac-d629e08f0bc3)

I'm completely new to po4a and to really familiar with the problem that could arise with this solve. Did anyone had issues with that too ?

Thanks a lot for all the work ! It's amazing !

**Comment by qwrtln** [comment]
Hi, thanks for reaching out. Mind creating a PR with this? I'll see if it breaks anything. BTW, what language are you translating to? You could join us so that your translation is versioned here.

**Comment by qwrtln** [comment]
Please write me on Discord (my username is the same over there). I'll help you get started.
