### ISSUE TITLE
Component list with pictures

### ISSUE THREAD

**Issue by DarthGandalf** [Heegu-sama/Homm3BG#188]
Like what is in official rule book

If the player is holding "something" in hand, to understand what he's holding - Is it an artifact or a spell? Is it a resource die or an attack die?

**Comment by qwrtln** [comment]
How exactly do you imagine this? If you just skim through the rule book, you can easily tell which component is which.

**Comment by DarthGandalf** [comment]
I need to skim over all the 50 pages for that. I'm just finding for one specific component (say, an event card)

**Comment by qwrtln** [comment]
I see. How about a single (last) page with a content like that?

**Comment by DarthGandalf** [comment]
If it can all fit on a single page.

But the last page is better used for something more useful.

**Comment by qwrtln** [comment]
I was thinking about info well hidden within the rule book, like the cost of surrendering, the cost of losing, the cost of transferring your units to town...
