### ISSUE TITLE
Rule clarifications/fix errors

### ISSUE THREAD

**Issue by Heegu-sama** [Heegu-sama/Homm3BG#20]
- [x] AI heroes flag all flaggable fields they happen to touch and mark all other visitable fields with black cubes. This needs to be explained. They only actively seek mines/settlements/the player/their town but will place cubes to any other field they happen to coincidentally cross. Alex K just confirmed this on discord.

- [x] Not happy with how starting combat with another player is defined with the two bullet points on page 21. I find the whole combat section difficult to structure TBH.

- [x] War machine factory is now pictured twice and I originally wrote that it won't be pictured below again on page 31. Probably explain its function with a picture of the war machine under expansion content, and cross-link between that part and the list of locations that shows the factory?

- [x] Expand random town's description to describe its full effect regarding choosing the bronze unit.

- [x] Complete restructure for page 31. Get rid of the screenshot and explain icons. (Maybe no need for this for now).

- [x] There's probably more spots where svg images could be placed for unit stars and types are mentioned. "Ground/flying/ranged units" can always be replaced with just the symbol IMO after they've been explained.

- [x] Fix capitalization in table of contents and remove numbers from section headings.

**Comment by qwrtln** [comment]
https://github.com/Heegu-sama/Homm3BG/pull/31 <- this moves war machine factory back to expansion content.
