### ISSUE TITLE
Spell Cards: Add clarification between basic spell cards and expert spell cards

### ISSUE THREAD

**Issue by lanarchyste** [Heegu-sama/Homm3BG#228]
In the original rules, the difference is explained only with an image

Some cards refer to expert spells, so it is interesting to clarify this subject.

For information: an expert card is a card with the symbol of the school of magic represented on all 4 sides of the illustration.

**Comment by qwrtln** [comment]
Is this not enough?

![image](https://github.com/Heegu-sama/Homm3BG/assets/5611195/5c402c82-decf-4f4a-ae3b-04311802a98f)

**Comment by lanarchyste** [comment]
My apologies, I didn't see that there was a section for extensions.
