### ISSUE TITLE
Optional rules table redo

### ISSUE THREAD

**Issue by DarthGandalf** [Heegu-sama/Homm3BG#235]
Currently it's done as image directly copied from official rules. But that's not translateable without making similar images

Need to make it latex table with text

**Comment by qwrtln** [comment]
I think a simple scan from translated original will do.

**Comment by qwrtln** [comment]
Making it in LaTeX will be a lot of work. But if you want to do it, nobody's stopping you.

**Comment by qwrtln** [comment]
There are three tables. Doing it once should cover all three cases.

**Comment by DarthGandalf** [comment]
WIP

![Выделение_534](https://github.com/Heegu-sama/Homm3BG/assets/325092/1d99ef3d-8ae5-41f1-9fa9-d94636aa4f9a)

I need to fix some margins.
I don't know how to add nice shadows like in the original table.

Current code:

```latex
\definecolor{darkcellborder}{HTML}{634831}
\newcommand{\darkcell}[1]{
        \begin{tikzpicture}
                \filldraw[thick, fill=black, fill opacity=0.5, draw=darkcellborder] (0, 0) rectangle (\linewidth, 1);
                \node at (current bounding box.center) {#1};
        \end{tikzpicture}
}

\definecolor{lightcellborder}{HTML}{77543e}
\newcommand{\lightcell}[1]{
        \begin{tikzpicture}
                \filldraw[thick, fill=black, fill opacity=0.2, draw=lightcellborder] (0, 0) rectangle (\linewidth, 1);
                \node at (current bounding box.center) {\color{white}#1};
        \end{tikzpicture}
}

\note{15}{
        \centering
        Trade Table
        \medskip

        \begin{tabularx}{\linewidth}{XXXX}
                \darkcell{\color{white}Sells/gets} & \darkcell{...to purchase \includesvg[height=10px]{\svgs/gold.svg}} & \darkcell{...to purchase \includesvg[height=10px]{\svgs/valuablegreater.svg}} & \darkcell{...to purchase \includesvg[height=10px]{\svgs/building_materials.svg}} \\
                \darkcell{I am selling \includesvg[height=10px]{\svgs/gold.svg}...} & \lightcell{--} & \lightcell{6 for 1} & \lightcell{2 for 1} \\
                \darkcell{I am selling \includesvg[height=10px]{\svgs/valuablegreater.svg}...} & \lightcell{1 for 3} & \lightcell{--} & \lightcell{1 for 2} \\
                \darkcell{I am selling \includesvg[height=10px]{\svgs/building_materials.svg}...} & \lightcell{1 for 3} & \lightcell{3 for 1} & \lightcell{--} \\
        \end{tabularx}
}

```

Though this particular table IMHO would better look like this:

![Выделение_535](https://github.com/Heegu-sama/Homm3BG/assets/325092/0dffe494-4da2-4836-8e87-f097c39d6a30)

**Comment by qwrtln** [comment]
Wow, looks very neat! But I like the original design better. Can't really tell what the second version means before knowing the original.

**Comment by DarthGandalf** [comment]
Hm, then probably I'll add the headers with text "selling", "purchase" back, and only replace the "X for Y" with these arrows with pictures
