### ISSUE TITLE
Defend

### ISSUE THREAD

**Issue by filip-cygan-kitopi** [Heegu-sama/Homm3BG#247]
Currently defend is stated like this 
"Units may choose to gain a Defense Token instead of attacking."
I think we should add 
"Units may choose to gain a Defense Token instead of attacking or moving."

Because we cannot move and than defend

**Comment by qwrtln** [comment]
Yes, we can.

**Comment by FCygan** [comment]
So I can always defend? Even if in the round it was impossible to attack, I can move half of the map and than defend?

**Comment by qwrtln** [comment]
I don't know what you mean by "impossible to attack", but yes, you can move and then defend.
