### ISSUE TITLE
Using combat related instant cards outside of combat

### ISSUE THREAD

**Issue by evilmint** [Heegu-sama/Homm3BG#250]
Recently one of the devs clarified that it is actually possible to use instant cards outside of combat, for example to discard cards

<img width="482" alt="Screenshot 2024-04-25 at 15 27 55" src="https://github.com/Heegu-sama/Homm3BG/assets/9850720/4d5e6600-e5bb-413d-a3c1-8836f3032c52">
<img width="519" alt="Screenshot 2024-04-25 at 15 28 12" src="https://github.com/Heegu-sama/Homm3BG/assets/9850720/55840ed7-54ce-4334-b7a4-d18718aff357">

This would mean this would have to be adjusted

<img width="309" alt="Screenshot 2024-04-25 at 15 31 14" src="https://github.com/Heegu-sama/Homm3BG/assets/9850720/ed8ff00a-1d2d-4cca-81bd-641445f94baf">

**Comment by Legrecofr** [comment]
Adding something like. "But has no effect since used outside of Combat"

**Comment by tomaas-zeman** [comment]
Fixed in https://github.com/Heegu-sama/Homm3BG/pull/504
