### ISSUE TITLE
Trading post

### ISSUE THREAD

**Issue by DarthGandalf** [Heegu-sama/Homm3BG#274]
![Выделение_538](https://github.com/Heegu-sama/Homm3BG/assets/325092/2ba3a708-f6cc-451a-9302-009cbf539c73)

**Comment by Legrecofr** [comment]
The rule in Rampart book  cause that :
"Allows the visiting Hero to exchange resources, Remove
a card, or buy a War Machine."

Every "," is a OR.

**Comment by qwrtln** [comment]
Stuff like that should be written by engineers 😆

**Comment by DarthGandalf** [comment]
AFAIK in English the word "or" doesn't imply mutually exclusive

**Comment by qwrtln** [comment]
Is there a word for exclusive or in English?

**Comment by Legrecofr** [comment]
Trading post is a revisitable site. It would be weird to do everything with just one Visit.
