### ISSUE TITLE
Mistakes in Polish translation - War Machines

### ISSUE THREAD

**Issue by JStanula** [Heegu-sama/Homm3BG#320]
Witam,
zauważyłem w polskim tłumaczeniu dwa dosyć istotne błędy. Na stronie 42, karta balisty. 

W wersji angielskiej;
"3. War Machine Factory cost" - odnosząca się do kosztu w złocie jaki trzeba zapłacić nabywając machinę wojenną w Fabryce Machin Wojennych
"4. Trading Post cost" - odnosząca się do kosztu w złocie jaki trzeba zapłacić nabywając machinę wojenną w Punkcie Handlowym

W wersji polskiej:
"3. Koszt zakupu"
"4. Koszt wymiany"

Więc jakiś poważny błąd się wkradł bo obie wartości to koszt zakupu tylko w dwóch różnych miejscach. 

![war machines](https://github.com/Heegu-sama/Homm3BG/assets/56120040/e1be9ede-ba67-42fd-9660-55a6cc8f4efe)

**Comment by qwrtln** [comment]
Naprawione w #322
