### ISSUE TITLE
Missing Example for Permanent Card Discart - Page 16

### ISSUE THREAD

**Issue by Kerlag21** [Heegu-sama/Homm3BG#330]
Hi All,

I think that it would be worth to add some additional example for Permanent Card Discarded - esspecialy concern War Machines. What happened when you Discarded War Machine (no matter which) Permanent card and replace it with other Permanent effect card. What happen with discarted this War Machine? You lose it and would have to buy once again or you should flip it? If you discart artefact this is quite obvious, but in case of War Machines it should be specified in my oppinion. Many thanks!

**Comment by DarthGandalf** [comment]
Any discard goes to the discard pile, unless it says "remove" - removing is out of game
