### ISSUE TITLE
[EN] Stars issues 

### ISSUE THREAD

**Issue by JStanula** [Heegu-sama/Homm3BG#347]
In the difficulty table on the last page of the PDF, there are multiple stars of the same colour with no digit. I think it should be a digit and one star of the colour like "2x(gold star)".

The other issue is that the stars now have a weird outline (black and gold). In previous versions it wasn't there. I'm not sure if this is intended or just a bug.

![Zrzut ekranu 2024-05-01 214434](https://github.com/Heegu-sama/Homm3BG/assets/56120040/fde98779-d002-452f-a528-07123e9a9c80)

**Comment by Legrecofr** [comment]
Yeah some people from french community also asked about that

**Comment by DarthGandalf** [comment]
Re stars without numbers - that's on me. I found it hard to read the original table. With the updated table, it's easier to glance at it to understand how many of which unit to draw.

But the border isn't supposed to be that thick. It should look like this:

![Выделение_550](https://github.com/Heegu-sama/Homm3BG/assets/325092/77adcfba-3d2b-471a-af39-933d633b5224)

Looks like different PDF readers render this border differently, and depending on zoom

**Comment by qwrtln** [comment]
I'll revert the yellow outline.

**Comment by qwrtln** [comment]
Fixed by #362
