### ISSUE TITLE
[PL] Tura gracza - podwójne zaprzeczenie

### ISSUE THREAD

**Issue by JStanula** [Heegu-sama/Homm3BG#360]
https://github.com/Heegu-sama/Homm3BG/blob/main/translations%2Fplayer_turns.tex%2Fpl.po#L264

W tym miejscu jest fragment 
"  Frakcja ta nie może pozyskać bądź stracić Morale z jakiegokolwiek powodu.\n"

Ale z racji tego, że w j.polskim istnieje tzw. podwójne zaprzeczenie to powyższe zdanie powinno wyglądać tak:
"  Frakcja ta nie może pozyskać, bądź stracić Morale z żadnego powodu.\n"

**Comment by qwrtln** [comment]
Dzięki, poprawię.

**Comment by qwrtln** [comment]
I raczej nie powinno być tam precinka 😁

**Comment by qwrtln** [comment]
Naprawione w #342
