### ISSUE TITLE
[PL] - brak l.mnogiej w przygotowaniu rozgrywki

### ISSUE THREAD

**Issue by JStanula** [Heegu-sama/Homm3BG#383]
Zauważyłem, że w polskim tłumaczeniu brak l.mnogiej w rozdziale "Przygotowanie Gry" punkt 4. 
"2 x Figurka Bohatera" powinno być "2 x Figurki Bohaterów"
"20 x Kostka Frakcji" powinno być "20 x Kostek Frakcji"
itd.

Nie wiem dlaczego autor zdecydował się na taką zmianę, skoro w oryginalnej instrukcji w j.polskim w punkcie 4 Przygotowania Gry są poprawne formy l.mnogiej.

**Comment by qwrtln** [comment]
Dzięki za zgłaszanie błędów. Proszę o nieocenianie pracy tłumaczy, to tylko ludzie ;-) Poprawimy.

**Comment by JStanula** [comment]
Nie chodziło mi o wytykanie błędów tylko bardziej sugestię, że przy tłumaczeniu warto wzorować się na oryginale bo mimo, że może nie jest ułożony idealnie to jeśli chodzi o tłumaczenie i stylistykę to jest na dobrym poziomie. Oczywiście szacun dla wszystkich zaangażowanych w ten projekt bo robicie kawał dobrej roboty.

**Comment by qwrtln** [comment]
Jak najbardziej tak robimy. Niemniej jednak pomyłki wciąż się zdarzają. Dzięki za zgłaszanie błędów 👍🏻

**Comment by qwrtln** [comment]
Fixed by #384
