### ISSUE TITLE
[PL] - wprowadzenie literówka

### ISSUE THREAD

**Issue by JStanula** [Heegu-sama/Homm3BG#385]
https://github.com/Heegu-sama/Homm3BG/tree/main/translations/introduction.tex/pl.po
linijka 101
jest "komopnentach " powinno być "komponentach"

PS. plus sugestia z mojej strony zamiast użyć słowa "rozwiązywane" dałbym "rozpatrywane"
Ale to tylko sugestia, nie błąd ;)

**Comment by qwrtln** [comment]
Dzięki, poprawię (fixed by #384)
