### ISSUE TITLE
check_pages job downloads too many artifacts

### ISSUE THREAD

**Issue by DarthGandalf** [Heegu-sama/Homm3BG#470]
Not only for the current language, but for all

![Выделение_564](https://github.com/Heegu-sama/Homm3BG/assets/325092/bbf6eb98-9457-4bbf-a7b2-7c4bc510a136)

**Comment by qwrtln** [comment]
Well, this is how the github action works. Not sure what you're expecting here?

**Comment by DarthGandalf** [comment]
To provide "name" or "pattern" to download only the current language (+en)

E.g. "check_pages (ru)" shouldn't be downloading printable_fr
