### ISSUE TITLE
🇨🇿 Czech translation

### ISSUE THREAD

**Issue by tomaas-zeman** [Heegu-sama/Homm3BG#556]
Original Czech rulebook https://archon-studio.com/files/manuals/homm/HoMM-Rulebook_CZ.pdf

Progress 
* [x] main_cs.tex https://github.com/Heegu-sama/Homm3BG/pull/557
* [x] ai_rules.tex https://github.com/Heegu-sama/Homm3BG/pull/583
* [x] all_map_locations.tex https://github.com/Heegu-sama/Homm3BG/pull/588
* [x] back_cover.tex https://github.com/Heegu-sama/Homm3BG/pull/573
* [x] combat.tex https://github.com/Heegu-sama/Homm3BG/pull/582
* [x] components.tex https://github.com/Heegu-sama/Homm3BG/pull/565
* [x] credits.tex https://github.com/Heegu-sama/Homm3BG/pull/573
* [x] deckbuilding.tex https://github.com/Heegu-sama/Homm3BG/pull/572
* [x] difficulty.tex https://github.com/Heegu-sama/Homm3BG/pull/584
* [x] expansion_content.tex https://github.com/Heegu-sama/Homm3BG/pull/587
* [x] game_modes.tex https://github.com/Heegu-sama/Homm3BG/pull/564
* [x] heroes.tex https://github.com/Heegu-sama/Homm3BG/pull/571
* [x] index.tex https://github.com/Heegu-sama/Homm3BG/pull/563
* [x] introduction.tex https://github.com/Heegu-sama/Homm3BG/pull/563
* [x] map_elements.tex https://github.com/Heegu-sama/Homm3BG/pull/576
* [x] notes.tex https://github.com/Heegu-sama/Homm3BG/pull/573
* [x] player_turns.tex https://github.com/Heegu-sama/Homm3BG/pull/570
* [x] quote_page.tex https://github.com/Heegu-sama/Homm3BG/pull/557
* [x] resources.tex https://github.com/Heegu-sama/Homm3BG/pull/574
* [x] round_structure.tex https://github.com/Heegu-sama/Homm3BG/pull/569
* [x] scenario_end.tex https://github.com/Heegu-sama/Homm3BG/pull/586
* [x] setup.tex https://github.com/Heegu-sama/Homm3BG/pull/566
* [x] title_page.tex https://github.com/Heegu-sama/Homm3BG/pull/557
* [x] town.tex https://github.com/Heegu-sama/Homm3BG/pull/575
* [x] trading.tex https://github.com/Heegu-sama/Homm3BG/pull/585
* [x] units.tex https://github.com/Heegu-sama/Homm3BG/pull/577

**Comment by qwrtln** [comment]
In the Czech version, the font in tables and note boxes seems off. It seems that `textbf` is not applied whatsoever. Could be something else too, but it's hard to tell just looking at the PDF file.

**Comment by tomaas-zeman** [comment]
Czech `subsections` have different top and bottom margins (too large) in comparison to other babels

**Comment by tomaas-zeman** [comment]
Images and cards from examples are not translated

**Comment by qwrtln** [comment]
> Czech `subsections` have different top and bottom margins (too large) in comparison to other babels

I guess Spanish suffers from that too. If you fix it, you'll shoot two birds with one stone.
