### ISSUE TITLE
Inconsistent PDF rendering in different programs after running GhostScript

### ISSUE THREAD

**Issue by tomaas-zeman** [Heegu-sama/Homm3BG#561]
I have never seen this before but for some reason, when opening the released PDF in a Chrome tab (internal PDF viewer) and in MacOS PDF viewer, I get different results

_Left: MacOS PDF viewer (Preview), Right: Chrome tab_
<img width="1150" alt="Screenshot 2024-06-06 at 21 07 31" src="https://github.com/Heegu-sama/Homm3BG/assets/1928291/a8e36e1f-827a-4c3e-9c86-95f95737b438">

Building the file locally without any optimizations produces a file that looks correct in both viewers.

<img width="983" alt="Screenshot 2024-06-06 at 21 13 18" src="https://github.com/Heegu-sama/Homm3BG/assets/1928291/1e3c4d5d-2848-4cd5-9db4-453c9e4392a0">

Only after I run `optimize.sh` and GhostScript tool, I can see that problem again.

**Comment by qwrtln** [comment]
Ghostscript 10 utilizes some bleeding-edge optimizations. Perhaps not every PDF reader is capable of rendering them properly. Mind trying the same with Ghostscript 9 to see if you get the same result?

**Comment by tomaas-zeman** [comment]
GS9 didn't help. It's either shadow or transparency issue I think but I was not able to find anything that could help to fix it
<img width="432" alt="Screenshot 2024-06-12 at 19 51 24" src="https://github.com/Heegu-sama/Homm3BG/assets/1928291/0e6ca730-de71-42f6-b2d1-cf9833da8c3c">

**Comment by qwrtln** [comment]
Ghostscript/MacOS preview/KDE Okular limitations. The only solution I can think of is baking those shadows in the images.
