### ISSUE TITLE
Improvements to text on AI combat

### ISSUE THREAD

**Issue by JorgenLjones** [Heegu-sama/Homm3BG#592]
1. Clarify that the AI will not have any walls or defensive structures if not explicitly stated in the scenario. [Confirmed by devs here](https://boardgamegeek.com/thread/3227959/article/43962848#43962848)
2. When the devs respond to [this question](https://boardgamegeek.com/thread/3227959/article/44422087#44422087), add which distance to use when determining which unit is closer.

### _Text edit suggestion specifically under AI Deck_
3. Remove the word 'automated' as it isn't any different to any other deck and could confuse the reader. 
> “AI Heroes use two automated Decks during Combat”
→
> “AI Heroes use two Decks during Combat”
4. Specify that the Spell Deck the AI will be using is separate to the regular Spell Deck.
> "the AI Deck, and the Spell Deck"
→
> "the AI Deck, and the AI Spell Deck"
5. Change 'is built using' to 'consist of' to avoid implying that one must do something special to “build” this deck.
> “The AI Deck is built using three types of AI cards: Might, Magic and Skill."
→
> “The AI Deck consists of three types of AI cards: Might, Magic, and Skill cards"
6. Clarify that the player has to ensure the correct cards are included in the AI Deck
> “Each Campaign scenario lists the number of each type of Card included in the AI Deck."
→
> “Each Campaign scenario lists the number and types of Cards to include during setup."
7. Delete the sentence “Might and Skill Cards have two variations” as it isn't essential information, and feels misplaced. Plus, Might cards have more than two variations, as not all Attack and Defence cards are identical.
8. Somewhat dependent on suggestion 7 above, simplify and be more assertive on selecting all cards at random. (Maybe even remove this sentence as well?)
> "Choose these cards randomly when building the Deck."
→
> "Shuffle the AI Deck to prepare it for setup."
9. Clarify that the scenario text will determine if Skill Cards are included. If suggestion 8 is implemented, then this sentence should come before it.
> "If Skill Cards are included, search for and set aside the Ability Card related to it."
→ 
> "If the Campaign scenario specifies an enemy Hero Ability: Find and set aside this Ability card and Include the Skill Cards to the AI Deck"
10. 
> "Build the AI’s Spell Deck by separating the indicated Spells from the regular Spell Deck.
→
> "If the Campaign scenario indicates any spells for the AI, find these Spell Cards, shuffle them and set them aside. This is now the AI Spell Deck."
11. Delete the last sentence of this paragraph: “Shuffle the AI and Spell Decks during setup after building them.”

_Suggestions 3 through 11 taken together: (icons omitted)_

AI Heroes use two automated Decks during
Combat: the AI Deck, and the Spell Deck. 
The AI Deck is built using three types of AI 
cards: Might, Magic and Skill. Each 
Campaign scenario lists the number of each 
type of Card included in the AI Deck. Might
and Skill Cards have two variations. 
Choose these cards randomly when build- 
ing the Deck. If Skill Cards are included, 
search for and set aside the Ability Card re- 
lated to it. Build the AI’s Spell Deck by 
separating the indicated Spells from the reg- 
ular Spell Deck. Shuffle the AI and Spell 
Decks during setup after building them.
→
AI Heroes use two Decks during Combat:
the AI Deck, and the AI Spell Deck. The 
AI Deck consists of three types of AI cards: 
Might, Magic, and Skill Cards. Each Campaign 
scenario lists the number and types of Cards 
to include during setup. If the Campaign 
scenario specifies an enemy Hero Ability: 
Find and set aside this Ability card and Include 
the Skill Cards to the AI Deck. Shuffle the AI 
Deck to prepare it for setup. If the Campaign 
scenario indicates any spells for the AI, find 
these Spell Cards, shuffle them and set them 
aside. This is now the AI Spell Deck.

_The character count decreases slightly from 596 to 579 with these changes_

**Comment by qwrtln** [comment]
Mostly fixed in #656
