### ISSUE TITLE
Decide on whether to use “Attack die” or “Combat die”

### ISSUE THREAD

**Issue by JorgenLjones** [Heegu-sama/Homm3BG#593]
The original rulebook doesn't use the term “Combat die”, but the rewrite uses this term instead of “Attack die” in the sections Using Cards During Combat (p.32) and Combat Round Structure (p. 34).

I actually prefer the term Combat die over Attack die because you sometime are asked to roll them when you aren't attacking, like to resolve a defence token. “Combat die” makes it less confusing, in my opinion. So an alternative to changing the non-original terms in the two sections pointed out above, I suggest defining “Combat die” in the same place where “Attack die” is introduced. We should probably explain that the original rulebook, and some cards, refer to Attack dice, but the rewrite uses the term Combat dice in its place. My guess is that most people who read Combat die will make the correct inference without thinking about it twice, but maybe I'm wrong, and it's a bad move to introduce a non-original term like this.

**Comment by Mirzipan** [comment]
Some of the card in the game (e.g. Crusaders, Champions, Zombies .. ) do reference the die as 'Attack die', therefore I think that 'Attack die' should be used instead of 'Combat die' in the rulebook as well.
