### ISSUE TITLE
Secondary Hero - Experience

### ISSUE THREAD

**Issue by FlavienBusseuil** [Heegu-sama/Homm3BG#623]
Hi there and thank you so much for the amazing job on this fan-made rulebook. So many clarifications :star_struck: !

Rulebook p. 15 says : _"They do not have their own Hero Card, cannot gain Experience, and cannot play Cards from Your Deck
during Combat."_

By saying "**cannot gain Experience**", it's pretty clear that the secondary hero has no individual experience track because it's preceded by _"They do not have their own Hero Card"_. So, secondary hero do not gain experience for himself but, and that's what is unclear to me, does the secondary hero collect experience for the primary hero by visiting location, rolling the treasure dice or winning combat ? This has a huge impact on secondary Hero power value.

I played ignoring any experience gain from the secondary hero and it felt a bit dumb some times. Rolling the treasure dice and getting an experience result can be frustrating.

Anyways, it may help rephrase the sentence in one way or another to clarify the intention.

**Comment by qwrtln** [comment]
Yes, this is exactly what happens. If you roll experience on a treasure die with your secondary hero, it is lost.
