### ISSUE TITLE
Clarification for retreating from combat

### ISSUE THREAD

**Issue by Dima793** [Heegu-sama/Homm3BG#624]
English rulebook mentions a player retreating from combat against neutral units, but doesn't explicitly clarify whether a player can do it proactively at will or not. From my experience with both Archon Discord and friends, many assume a player can choose to retreat on any of their unit activation. Moreover, Polish rulebook directly says a player can retreat at any time.

However, it was [clarified](https://discord.com/channels/740870068178649108/1211591995328299038/1232580702772531240) by Alex K (of Archon) that there is no option to retreat from a combat against neutral units, other than letting it end at the end of a round by not spending a Movement Point to prolong it (against non-azure units). And that the Polish rulebook translation [is erroneous](https://discord.com/channels/740870068178649108/1211591995328299038/1232580288840863754).
![Screenshot_20240629-113734_Discord](https://github.com/Heegu-sama/Homm3BG/assets/17815003/196ecb60-c723-4594-b92c-efde1a10c6ab)

I suggest this should be made more clear in the rewritten rulebook. 
One way would be to adjust "end of combat" section (p. 34) wording, for example adding a sentence like "You cannot Retreat proactively" at the end of its first paragraph. Conveniently, there is just enough free space on its last line.
![image](https://github.com/Heegu-sama/Homm3BG/assets/17815003/8c8790ba-3a88-4d63-a933-08f257fcfb13)

**Comment by DarthGandalf** [comment]
See #629
