### ISSUE TITLE
Recruitment of Azure tier

### ISSUE THREAD

**Issue by captain-yoshi** [Heegu-sama/Homm3BG#633]
It would be nice to have this information.

![image](https://github.com/Heegu-sama/Homm3BG/assets/32679594/59958567-60ae-4474-85b6-a87e0eebf550)

![image](https://github.com/Heegu-sama/Homm3BG/assets/32679594/a8d6a043-54c9-4802-9ed1-c54bc2214416)

**Comment by qwrtln** [comment]
See #647
