### ISSUE TITLE
Screenshots got moved

### ISSUE THREAD

**Issue by Daar543** [Heegu-sama/Homm3BG#692]
The PR #690 has changed the output of the script `pdf2image.sh` to the `screenshots` folder, good if that was reflected in the README. 
I spent some bit of time figuring out where did the files go; normally I would consider it clear but since it occured as part of recent change, it would make sense to update in README too.

**Comment by qwrtln** [comment]
Sorry about that, let me fix it.

**Comment by qwrtln** [comment]
Fixed by #695, [this is the commit](https://github.com/Heegu-sama/Homm3BG/pull/695/commits/4efe90a1f3b2e8995c7578ac07d2b395739aee54).
