### ISSUE TITLE
Polish version error

### ISSUE THREAD

**Issue by KrzysztofBiedron** [Heegu-sama/Homm3BG#700]
In the Polish translation there is an error on the page 41.
Current Version:
W Punkcie Handlowym nie możesz usunąć Kart Specjalności, 
Statystyk, Zdolności ani Zaklęcia
 „Magiczna Strzała”.
Should be:
W Punkcie Handlowym nie możesz usunąć Kart Specjalności, 
Statystyk, Zdolności **początkowej** ani Zaklęcia
 „Magiczna Strzała”.

**Comment by qwrtln** [comment]
Fixed by #701
