### ISSUE TITLE
Range penalty from walls

### ISSUE THREAD

**Issue by omoprof** [Heegu-sama/Homm3BG#76]
accroding to one of the designers [here ](https://boardgamegeek.com/thread/3227959/official-faq-thread/page/4)

"The damage penalty only applies to ranged attacks if the attacked unit is behind a wall (behind the wall/gate line), and there is at least one undestroyed wall/gate on the map."

pentalty should always applied as long as there are one wall tile alive, regardless of line of fire.

**Comment by qwrtln** [comment]
Are you sure about this? What you're quoting is just a brief simplification. It's better explained in [this thread](https://boardgamegeek.com/thread/3166470/rule-questions-part-1).

Note that this rule book does not utilise the term "line of sight/fire".

**Comment by omoprof** [comment]
> Are you sure about this? What you're quoting is just a brief simplification. It's better explained in [this thread](https://boardgamegeek.com/thread/3166470/rule-questions-part-1).

Of course I am not sure. That is the whole point of making this)

From link you gave me:
"Units get this penalty to attack if the enemy is "behind" a wall or gate. So behind an obstacle called a wall or gate. Any "holes" on the sides are not important. You just check the rows. It is an even simpler mechanic than even the most basic LOS rules, but worked better in the tests so we kept it. "

if you scroll down a few posts:

"Because we do not use line of sight here and simplify it in this game, everyone behind the line of the wall gets this additional protection.

So if the target is in the same column as the wall, and on the opposite side of the map, the protection is in effect. They are "behind a wall. ..."

**Comment by qwrtln** [comment]
All right, cheers.

**Comment by omoprof** [comment]
@qwrtln Edited my comment, did I got that correctly?

**Comment by qwrtln** [comment]
No, you only check the defender column. Attacker's column doesn't matter. Should it be better explained in this rule book?

**Comment by omoprof** [comment]
@qwrtln 
It's fine, my misunderstading came from that first comment.

**Comment by qwrtln** [comment]
Where exactly would you put those checkmarks? Can you draft an example?

**Comment by omoprof** [comment]
@qwrtln Where numbers are, below or on top?. I assume it would be more clear than reading below that 1-8 are protected/not protected

**Comment by omoprof** [comment]
and line between unit and a wall maybe, green when protected, red when not

**Comment by qwrtln** [comment]
Well, numbers 1-8 are not protected or not protected, they are the fields you're supposed to be attacking from.

**Comment by qwrtln** [comment]
OK, that second part might be useful, highlight "protected" fields with green colour maybe.

**Comment by omoprof** [comment]
something like that, yes

**Comment by qwrtln** [comment]
Thanks, I'll leave this open for reference,

**Comment by omoprof** [comment]
![maybe](https://github.com/Heegu-sama/Homm3BG/assets/112781109/7aeddbfd-c73f-4a37-8404-13bf04c86109)
something like this maybe? (Not an artist)

**Comment by omoprof** [comment]
![maybe](https://github.com/Heegu-sama/Homm3BG/assets/112781109/746f560c-99af-4596-9eaf-afb6be35e8dd)

**Comment by qwrtln** [comment]
Are you familiar with Gimp? Would you be interested in doing this yourself?

**Comment by omoprof** [comment]
image above is best I can do, so no) Never had a feel for graphic design

**Comment by Heegu-sama** [comment]
> accroding to one of the designers [here ](https://boardgamegeek.com/thread/3227959/official-faq-thread/page/4)
> 
> "The damage penalty only applies to ranged attacks if the attacked unit is behind a wall (behind the wall/gate line), and there is at least one undestroyed wall/gate on the map."
> 
> pentalty should always applied as long as there are one wall tile alive, regardless of line of fire.

Yes, I can certainly see how reading the latter part of that sentence could confuse you. Obviously there needs to be an undestroyed wall/gate so that units can even have the chance to hide behind it in the first place. 😄

**Comment by qwrtln** [comment]
![image](https://github.com/Heegu-sama/Homm3BG/assets/5611195/c60a466a-e039-4a71-8eeb-c37bdfe53071)

**Comment by qwrtln** [comment]
![image](https://github.com/Heegu-sama/Homm3BG/assets/5611195/7385f13c-7401-4c49-a183-029ed030670a)

**Comment by omoprof** [comment]
looks good
