### ISSUE TITLE
Clarification on visitable tiles

### ISSUE THREAD

**Issue by omoprof** [Heegu-sama/Homm3BG#80]
Someone asked on bgg if you can skip tree of knowledge if you don't have resources to pay and use it later.

I propose to add something like this: If you land on visitable tile, you are forced to visit it and use it's effects. If you can't (ex not enough resources to pay for the tree), place a black cube on it without using it's effects.

(I can't really properly explaing things, so rewording is required)

**Comment by omoprof** [comment]
Same with flaggable, I guess, unless it's allied

**Comment by Heegu-sama** [comment]
Just chatted about this on discord. When you visit a "visitable" location, you have to place a black cube there. This is done even if you can't pay for the effect of that field or choose not to use the field's effects (if it has the wording "you may" or "you can").

This is a good thing to clarify, thanks for bringing it up.

**Comment by Heegu-sama** [comment]
Added a clarification box in latest PR.
